# Generated by AI from entrypoint.py

$pathOptions = @('admin', 'reports')

do {
    $pathChoice = Read-Host "`nDo you want to run [admin] or [reports]?" | ForEach-Object { $_.ToLower().Trim() }

    if (-not ($pathChoice -in $pathOptions)) {
        Write-Host "Invalid entry" -ForegroundColor Red
    }
} while (-not ($pathChoice -in $pathOptions))

if ($pathChoice -eq 'admin') {
    Write-Host "admin"
} elseif ($pathChoice -eq 'reports') {
    Write-Host "reports"
}